name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.4 ]
        include:
          - laravel: 11
            testbench: 9.14
          - laravel: 12
            testbench: 10.0
          - laravel: 13
            testbench: 11.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL

      - name: Set Laravel Version
        run: composer require "laravel/framework:^${{ matrix.laravel }}" "orchestra/testbench:^${{ matrix.testbench }}" --no-update

      - name: Install dependencies
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Validate Composer manifest
        run: composer validate --strict

      - name: Execute style
        run: composer run style

      - name: Execute tests
        run: composer run test
